#!/usr/bin/env bash
set -e
 
if [ "$1" = "-" ]; then
    echo git switch -;
elif [ "$1" = "-c" ]; then
    echo git switch -c $2;
elif [ "$1" = "--rb" ]; then
    branch=$(echo "$2" | sed 's|^[^:]*:||');
    git fetch origin "$branch" && echo git switch --track "origin/$branch";
elif [ -n "$1" ]; then
    git for-each-ref refs/heads --sort=-committerdate --format='%(refname:short) %(committerdate:relative) %(authorname)' | \
    grep -i "$1" | head -n 1 | awk '{print $1}' | xargs -r echo git switch;
else
    git for-each-ref refs/heads --sort=-committerdate --format='%(refname:short) | %(committerdate:relative) | %(authorname)' | \
    column -t -s '|' | \
    fzf --height=40 --layout=reverse --border --preview='git log --oneline --color=always -n 5 $(echo {} | awk "{print \$1}")' --preview-window=right:50% \
    | awk '{print $2}' | xargs -r echo git switch;
fi;

